apiVersion: v2
kind: Service
metadata:
    name: mvc-entrypoint
    namespace: default
spec:
    type: NodePort
    selector:
        mvc: web
    ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000