apiVersion: v1
kind: Service
metadata:
    name: "scfitzgek8sclusterv2-21e5"
    labels:
        app: "scfitzgek8sclusterv2-21e5"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "scfitzgek8sclusterv2-21e5"